[executor.direct]
type = "Local"
staging_mode = "Copy"

[executor.slurm]
type = "Slurm"
staging_mode = "Copy"
modules = ["gcc", "cuda"]
account = "st-shallam-1-gpu"
nodes = 1
tasks = 1
cpus = 12
memory = { type = "per_node", amount = 64000 }
gpus = 1
time = { hours = 6 }

[inputs]
input_files = ["data/1v9e_ph4.pdb", "data/1v9e_ph10.pdb"]
